### ISSUE TITLE
月总结 2021

### ISSUE THREAD

**Issue by hylarucoder** [twocucao/the-road-to-fitness#14]

**Comment by hylarucoder** [comment]
# 2021-04

体重 180 -> 169

**Comment by hylarucoder** [comment]
# 2021-05

169 -> 164

**Comment by ggggarlic** [comment]
## 2021-05 
165.4 -> 161.7

**Comment by ggggarlic** [comment]
## 2021-06
161 -> 157

**Comment by hylarucoder** [comment]
## 2021-06

164 -> 164

草了 一斤没减

**Comment by ggggarlic** [comment]
## 2021-07
157 -> 157 

就没动...  也不是什么坏事情.

**Comment by hylarucoder** [comment]
## 2021-07

164 -> 163.8

草了 第二个月一斤没减
