### ISSUE TITLE
记录 2021-05

### ISSUE THREAD

**Issue by hylarucoder** [twocucao/the-road-to-fitness#17]

**Comment by hylarucoder** [comment]
## 05-01

## 锻炼

- [x] 跑步8KM

## 饮食

- 早餐: 炸鸡 + 饼干
- 午餐: 饺子
- 晚餐: 西瓜

## 体重

169.8 斤

**Comment by hylarucoder** [comment]
## 05-02

## 锻炼

- [x] 跑步8KM

## 饮食

- 早餐: 鸡胸肉
- 午餐: 三菜无饭
- 晚餐: 鸡胸肉

## 体重

169.0 斤

**Comment by hylarucoder** [comment]
## 05-03

## 锻炼

- [x] 步行6km

## 饮食

- 早餐: 无
- 午餐: 鸡胸肉 + 咖啡
- 晚餐: 鸡胸肉 + 咖啡

## 体重

169.0 斤

**Comment by hylarucoder** [comment]
## 05-04

## 锻炼

- [x] 步行6km

## 饮食

- 早餐: 无
- 午餐: 鸡胸肉 
- 晚餐: 鸡胸肉 + 咖啡 + 全家桶

## 体重

170.0 斤

**Comment by hylarucoder** [comment]
## 05-05

## 锻炼

- [x] 步行4km

## 饮食

- 早餐: 无
- 午餐: 鸡胸肉 
- 晚餐: 鸡胸肉 + 鸡爪 + 牛奶

## 体重

170.0 斤

**Comment by ggggarlic** [comment]
## 05-06

## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  无
午餐:  拉面
晚餐:  煮饺子

## 体重
165.4 斤
> 5.1 家里来客人了 ...  几乎都是带娃出去玩了 .   昨天还食物中毒发烧来着.

**Comment by hylarucoder** [comment]
## 05-06

## 锻炼

- [x] 5000跳绳
- [x] 20min自行车
- [x] 20min自行车

## 饮食

- 早餐: 牛奶 + 美式
- 午餐: 三菜
- 晚餐: 鸡胸肉 + 半块饼

## 体重

171.0 斤

**Comment by hylarucoder** [comment]
## 05-07

## 锻炼

- [x] 2500跳绳
- [x] 20min自行车
- [x] 20min自行车

## 饮食

- 早餐: 牛奶 + 美式 + 鸡胸肉 + 半块饼
- 午餐: 三菜
- 晚餐: 鸡胸肉 + 半块饼

## 体重

170.0 斤

**Comment by ggggarlic** [comment]
## 05-07

## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  红面馒头
午餐:  
晚餐:  蘑菇炒肉

## 体重
163.5

**Comment by hylarucoder** [comment]
## 05-08

## 锻炼

- [x] 1500跳绳
- [x] 20min自行车
- [x] 7000跳绳
- [x] 20min自行车

## 饮食

- 早餐: 牛奶 + 美式 + 鸡胸肉
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

169.0 斤

**Comment by ggggarlic** [comment]
## 05-08

## 锻炼

- [x] 跳绳 4000

## 饮食
早餐:  燕麦 + 美式咖啡
午餐:  无
晚餐:  鸡腿  + 西蓝花  

## 体重
162.0

**Comment by hylarucoder** [comment]
## 05-09

## 锻炼

- [x] 4500跳绳

## 饮食

- 早餐: 牛奶 + 鸡胸肉
- 午餐: 饺子
- 晚餐: 炸鸡

## 体重

168 斤

**Comment by ggggarlic** [comment]
## 05-09

## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  蛋挞面包一片 + 美式咖啡
午餐:  青椒炒肉  + 米饭一大碗 +  蛋糕 100g
晚餐:  烧烤


## 体重
162.0


恢复食欲了，今天外出给女儿的小朋友庆生。

**Comment by hylarucoder** [comment]
## 05-10

## 锻炼

- [x] 6000跳绳
- [x] 20 min 骑车
- [x] 20 min 骑车

## 饮食

- 早餐: 牛奶 + 鸡胸肉
- 午餐: 沙拉轻食
- 晚餐: 牛奶

## 体重

168 斤

**Comment by ggggarlic** [comment]
## 05-09

## 锻炼

- [x] 跳绳 7000

## 饮食
早餐:  无
午餐:  拉面一碗
晚餐:  龙利鱼 + 西蓝花 + 1/3 米饭


## 体重
163.6

**Comment by ggggarlic** [comment]
## 05-10

## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  无
午餐:  肠粉
晚餐:   豆干炒肉 + 胡萝卜炒蘑菇 + 秋葵 + 1/3 米饭


## 体重
161.5

ps: 跳绳直接被我跳坏了, 里面的钢筋漏出来了 ... 李宁京东店还是很不错的, 直接给换绳子了. 

哦对了,  金属手柄的绳子一定要自己再加购买一下手胶. 不然在跳绳过程中特别容易落汗并且影响跳绳体验.

**Comment by hylarucoder** [comment]
## 05-11

## 锻炼

- [x] 5000跳绳
- [x] 20 min 骑车
- [x] 20 min 骑车

## 饮食

- 早餐: 牛奶 + 鸡胸肉
- 午餐: 沙拉轻食
- 晚餐: 牛奶

## 体重

167.4 斤

**Comment by hylarucoder** [comment]
## 05-12

## 锻炼

- [x] 5000跳绳
- [x] 20 min 骑车
- [x] 20 min 骑车

## 饮食

- 早餐: 牛奶 + 鸡胸肉
- 午餐: 沙拉轻食
- 晚餐: 面包

## 体重

166 斤

**Comment by hylarucoder** [comment]
## 05-13

## 锻炼

- [x] 5000跳绳
- [x] 20 min 骑车
- [x] 20 min 骑车

## 饮食

- 早餐: 半块面包 + 鸡胸肉
- 午餐: 沙拉轻食
- 晚餐: 牛奶

## 体重

166 斤

**Comment by hylarucoder** [comment]
## 05-14

休息一天

## 锻炼

- [x] 20 min 骑车
- [x] 20 min 骑车

## 饮食

- 早餐: 半块面包 + 鸡胸肉
- 午餐: 沙拉轻食
- 晚餐: 鸡胸肉 + 面包 + 炸鸡

## 体重

165.4 斤

**Comment by hylarucoder** [comment]
## 05-15

## 锻炼

- [x] 8600跳绳

## 饮食

- 早餐: 生煎+沙拉
- 午餐: 炸鸡
- 晚餐: 啤酒+炒菜

## 体重

167 斤

**Comment by hylarucoder** [comment]
## 05-16

## 锻炼

## 饮食

- 早餐: 生煎
- 午餐: 面条
- 晚餐: 饺子

## 体重

168 斤

**Comment by hylarucoder** [comment]
## 05-17

## 锻炼

- [x] 跑步6公里
- [x] 2x20min自行车

## 饮食

- 早餐: 牛奶+苹果
- 午餐: 沙拉
- 晚餐: 牛奶+苹果

## 体重

168 斤

**Comment by hylarucoder** [comment]
## 05-18

## 锻炼

- [x] 跑步5公里
- [x] 2x20min自行车

## 饮食

- 早餐: 梅干菜
- 午餐: 酸菜鱼
- 晚餐: 牛奶

## 体重

166.6 斤

**Comment by hylarucoder** [comment]
## 05-19

## 锻炼

- [x] 跑步5公里
- [x] 2x20min自行车

## 饮食

- 早餐: 司康+咖啡
- 午餐: 沙拉
- 晚餐: 牛奶

## 体重

165.6 斤

**Comment by ggggarlic** [comment]
## 05-14

## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  肠粉
午餐:  鹅肉  
晚餐:   自助餐


## 体重
160.2


ps: 跳绳坏了直接买了配件,   重新开始运动起来了.

**Comment by ggggarlic** [comment]
## 05-19

## 锻炼

- [x] 跳绳 1000

## 饮食
早餐:  肠粉
午餐:  无  
晚餐:   春饼


## 体重
162.1


ps:  完蛋, 上周面试接的有些多, 加上天气炎热 直接感冒了...  休息一周... 去了发热门诊看病是真的方便. 做了核酸和 CT 直接免费.

**Comment by hylarucoder** [comment]
## 05-20

## 锻炼

- [x] 跑步5公里
- [x] 2x20min自行车

## 饮食

- 早餐: 豆浆+包子x2
- 午餐: 沙拉
- 晚餐: 桃子+鸡胸肉

## 体重

165.8 斤

**Comment by hylarucoder** [comment]
## 05-21

## 锻炼

- [ ] 跑步5公里
- [x] 2x20min自行车

## 饮食

- 早餐: 鸡胸肉+桃子+牛奶
- 午餐: 沙拉
- 晚餐: 鸡胸肉

## 体重

164.8 斤

**Comment by ggggarlic** [comment]
## 05-20

## 锻炼
咳嗽中...   无锻炼...

## 饮食
早餐:  肠粉
午餐:  素菜沙拉
晚餐:   1/3 米饭 + 炒蘑菇 + 炒山药


## 体重
163

**Comment by ggggarlic** [comment]
## 05-21

## 锻炼

- [x] 跳绳 5000


## 饮食
早餐:  无
午餐:  炒虾 + 1/3 红薯米饭 + 炒蒜薹 + 炒西葫芦
晚餐:   炒胡萝卜 + 1/3 米饭 + 炒土豆丝


## 体重
161.1

**Comment by ggggarlic** [comment]
## 05-22

## 锻炼

- [x] 跳绳 2000


## 饮食
早餐:  无
午餐:  
晚餐:   


## 体重
162.2

**Comment by ggggarlic** [comment]
## 05-23

## 锻炼

- [x] 跳绳2000


## 饮食
早餐:  馒头 + 南瓜粥 + 煮鸡蛋 
午餐:  方便面
晚餐:   胡萝卜 + 西蓝花


## 体重
161.2

**Comment by hylarucoder** [comment]
## 05-22

## 锻炼

- 无

## 饮食

- 早餐: 鸡胸肉+牛奶
- 午餐: 啤酒+锅巴
- 晚餐: 鸡胸肉

## 体重

165.0 斤

**Comment by hylarucoder** [comment]
## 05-23

## 锻炼

- [x] 走路5公里

## 饮食

- 早餐: 鸡胸肉 + 锅巴
- 午餐: 无
- 晚餐: 面条

## 体重

166.5 斤

**Comment by hylarucoder** [comment]
## 05-24

## 锻炼

- [x] 跑步5公里
- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 美式
- 午餐: 沙拉
- 晚餐: 牛奶

## 体重

166.5 斤

**Comment by ggggarlic** [comment]
## 05-24

## 锻炼

- [x] 跳绳 5000
- [x] 无氧 Hit 10 min 

## 饮食
早餐:  无
午餐:  鸡腿 + 西蓝花
晚餐:   方便面


## 体重
160.7

> 明天开始上班啦， 希望可以继续坚持下去

**Comment by hylarucoder** [comment]
## 05-24

## 锻炼

- [x] 跑步5公里 
- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 鸡胸肉卷饼 + 牛奶
- 午餐: 沙拉
- 晚餐: 

## 体重

162.2 斤

**Comment by ggggarlic** [comment]
## 05-25

## 锻炼

- [x] 跳绳 3000


## 饮食
早餐:  肠粉 + 黑咖啡
午餐:  西兰花 + 烤鸭 + 上海青
晚餐:  方便面


## 体重
160.9

**Comment by hylarucoder** [comment]
## 05-26

今天下雨, 没有骑车

跑步改为无氧运动

## 锻炼

- [x] 跳绳 3000
- [x] 哑铃 100

## 饮食

- 早餐: 鸡胸肉卷饼
- 午餐: 沙拉
- 晚餐: 鸡胸肉卷饼

## 体重

161.6 斤

**Comment by ggggarlic** [comment]
## 05-26

## 锻炼

- [x] 跳绳 3000


## 饮食
早餐:  黑咖啡
午餐:  牛肉火锅 + 下午茶 蛋糕
晚餐:  无骨鸡爪


## 体重
 160.7

> !!!!!!!!!! 体重不动啦!!!!!!!!!!!!!!!!!!!

**Comment by ggggarlic** [comment]
## 05-27

## 锻炼

- [x] 跳绳 3000


## 饮食
早餐:  黑咖啡 + 小米粥
午餐:  蔬菜沙拉
晚餐:  烧烤 1/3 


## 体重
160.8 斤

**Comment by hylarucoder** [comment]
## 05-27

## 锻炼

- [x] 跑步
- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 鸡蛋培根卷饼
- 午餐: 沙拉
- 晚餐: 鸡胸肉卷饼

## 体重

162 斤

**Comment by ggggarlic** [comment]
## 05-28

## 锻炼

- [x] 跳绳 3000


## 饮食
早餐:  黑咖啡 + 小米粥
午餐: 蔬菜沙拉
晚餐: 披萨 1/2


## 体重
 160.9斤

**Comment by hylarucoder** [comment]
## 05-28

晚上聚会暴饮暴食....

## 锻炼

- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 鸡蛋培根卷饼
- 午餐: 沙拉
- 晚餐: 龙虾聚会

## 体重

166 斤

**Comment by ggggarlic** [comment]
## 05-29

## 锻炼
无


## 饮食
早餐:  火山荔枝
午餐:  小龙虾 + 1/3 米饭
晚餐:  烧烤 + 炒米粉 +啤酒


## 体重
 163.5

**Comment by ggggarlic** [comment]
## 05-30

## 锻炼
- [x] Bilibili 减脂操 10min


## 饮食
早餐:  火山荔枝
午餐:  小龙虾 + 啤酒 + 炒面
晚餐:  无


## 体重
 162.0

**Comment by hylarucoder** [comment]
## 05-29

## 锻炼

无

## 饮食

- 早餐: 包子x2
- 午餐: 韭菜盒子x2
- 晚餐: 韭菜盒子x2

零食若干

## 体重

165.0 斤

**Comment by hylarucoder** [comment]
## 05-30

## 锻炼

- [x] 跑步
- [ ] 骑车20min
- [ ] 骑车20min

## 饮食

- 早餐: 鸡胸肉卷饼
- 午餐: 韭菜盒子x2
- 晚餐: 韭菜盒子x2

零食若干

## 体重

164.0 斤

**Comment by hylarucoder** [comment]
## 05-31

又是胡吃海喝的一天

## 锻炼

- [x] 跑步
- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 美式+鸡胸肉
- 午餐: 沙拉
- 晚餐: 无



## 体重

166.0 斤

**Comment by ggggarlic** [comment]
## 05-31

## 锻炼
- [x] Bilibili 减脂操 10min
- [x] 跳绳 1000


## 饮食
早餐:  小米粥
午餐:  西兰花 ➕ 芋头
晚餐:  烧烤 ➕ 炒豆腐 ➕ 1/3米饭


## 体重
 161.7
