### ISSUE TITLE
2022-05

### ISSUE THREAD

**Issue by hylarucoder** [twocucao/the-road-to-fitness#26]
# 0324

## 饮食

1. 早: 牛奶+咖啡+苹果
2. 中: 牛排+橙子x2
3. 晚: 未吃

## 体重

80.4KG

**Comment by ggggarlic** [comment]
# 0324

## 饮食
- 早: 咪咪虾条 + 干脆面
- 中: 牛肉火锅 (素菜居多)
- 晚: 鸡蛋 x 4

## 体重

**Comment by hylarucoder** [comment]
# 0325

## 饮食

1. 早: 牛奶+咖啡+苹果
2. 中: 烙饼 + 鱼肉
3. 晚: 牛奶 + 鸡蛋

## 体重

79.6 KG (早)

**Comment by kii-la** [comment]
![image](https://user-images.githubusercontent.com/12641585/160250276-6a8e3953-4176-4493-9b43-f7bed810c47c.png)

**Comment by ggggarlic** [comment]
![image](https://user-images.githubusercontent.com/12641585/160250328-60f46019-9a90-40fc-abd1-749fa72ea0ef.png)

**Comment by hylarucoder** [comment]
# 0327

## 饮食

1. 早: 三明治 + 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 牛奶 + 牛排

## 锻炼

跳绳 半小时 + 划船机半小时

## 体重

80.2 KG (早)

**Comment by hylarucoder** [comment]
# 0328

## 饮食

1. 早: 三明治 + 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 牛奶 + 三明治

## 锻炼

跳绳 半小时 + 划船机半小时

## 体重

80.4 KG (早)

**Comment by ggggarlic** [comment]
![Screenshot_20220329-011141.jpg](https://user-images.githubusercontent.com/12641585/160451643-7f868e05-6193-4e2c-abb1-9d8b074da1a7.jpg)

**Comment by hylarucoder** [comment]
# 0329

## 饮食

1. 早: 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 烧烤+奶茶

## 锻炼

无

## 体重

80.7 KG (早)

**Comment by ggggarlic** [comment]
![image](https://user-images.githubusercontent.com/12641585/160667486-3b61ce0f-ea31-483d-980a-7df5a766ffa0.png)

**Comment by hylarucoder** [comment]
# 0330

## 饮食

1. 早: 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 苹果x1

## 锻炼

- 有绳跳绳30min + 无绳跳绳2000

## 体重

81.3 KG (早重, 昨天吃的太多了....)

**Comment by hylarucoder** [comment]
# 0331

## 饮食

1. 早: 牛排+鸡蛋+吐司
2. 中: 正常饮食
3. 晚: 苹果x1

## 锻炼


## 体重

80.5 KG (早)

**Comment by ggggarlic** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/12641585/161186297-9b30a73f-48cb-4240-bbe9-0cc6c335737e.png">

这两天在忙活服务器的事情...  没锻炼了先.   每天睡得都好晚.

**Comment by hylarucoder** [comment]
# 0401

## 饮食

1. 早: 
2. 中: 正常饮食
3. 晚: 面包 + 橘子

## 锻炼

- 划船机

## 体重

81 KG (早)

**Comment by ggggarlic** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/12641585/162168065-ff5c88ff-12a1-46be-a727-a3aecd07c8ee.png">

**Comment by hylarucoder** [comment]
# 0406

> 最近减肥效率太低, 决定砍掉1/3饮食

## 饮食

1. 早: 面条+咖啡
2. 中: 正常饮食
3. 晚: 牛排

## 锻炼

- 划船机

## 体重

81  KG (早)

**Comment by hylarucoder** [comment]
# 0407

> 最近减肥效率太低, 决定砍掉1/3饮食

## 饮食

1. 早: 包子x1+咖啡+豆浆
2. 中: 正常饮食
3. 晚: 

## 锻炼

- 

## 体重

80.4  KG (早)

**Comment by hylarucoder** [comment]
# 0409

## 饮食

1. 早: 包子x1 + 牛奶
2. 中: 正常饮食
3. 晚: 包子x2 + rio 鸡尾酒

## 锻炼

- 划船机

## 体重

80.1  KG (早)

**Comment by hylarucoder** [comment]
# 0411

## 饮食

1. 早: 包子x2 + 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 包子x2

## 锻炼

- 划船机

## 体重

81.3  KG (早, 昨天喝水太多了, 算是异常值吧....)

**Comment by hylarucoder** [comment]
# 0417

## 饮食

1. 早: 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 

## 锻炼

- 划船机 40min

## 体重

79.2  KG

**Comment by hylarucoder** [comment]
# 0420

## 饮食

1. 早: 牛奶 + 咖啡
2. 中: 正常饮食
3. 晚: 

## 锻炼

- 椭圆机 40min

## 体重

79.2  KG

**Comment by hylarucoder** [comment]
# 0531

## 饮食

## 锻炼

动感单车

## 体重

78.2  KG
