### ISSUE TITLE
记录 2021-04

### ISSUE THREAD

**Issue by hylarucoder** [twocucao/the-road-to-fitness#7]

**Comment by hylarucoder** [comment]
## 03-29

## 锻炼

![image](https://user-images.githubusercontent.com/5625783/112852669-b9d7d000-90de-11eb-8f4a-4c2592e937da.png)

- 早上 40min 健身环 + 20min自行车
- 晚上 40min 健身环 + 20min自行车

## 饮食

- 早餐: 美式拿铁+面包
- 午餐: 三菜, 不吃米饭
- 晚餐: 两瓶元气水

**Comment by hylarucoder** [comment]
## 03-30
## 锻炼

![image](https://user-images.githubusercontent.com/5625783/112915029-07c8f400-9130-11eb-8ab7-2f8bbe0dc9c0.png)

- [x] 早上 1小时健身环+20分钟自行车 (主深蹲)
- [x] 晚上 半小时健身环+20分钟自行车 (主手臂)

## 饮食

- 早餐: 美式拿铁+面包
- 午餐: 三菜, 不吃米饭
- 晚餐: 鸡胸肉+脱脂牛奶

**Comment by hylarucoder** [comment]
## 03-31
## 锻炼

- [x] 早上 1小时健身环+20分钟自行车 (主深蹲)
- [x] 晚上 20分钟自行车 (主手臂)

## 饮食

- 早餐: 美式拿铁+面包+脱脂牛奶
- 午餐: 三菜, 不吃米饭
- 晚餐: 速食面+橙子x2+鸡尾酒

**Comment by hylarucoder** [comment]
## 04-01

## 锻炼

- 健身环 200 深蹲 + 40min 健身环 + 20 min 自行车
- 20 min 自行车 + 500 推拉健身环

## 饮食

- 早餐: 美式拿铁
- 午餐: 三菜, 半碗米饭
- 晚餐: 蒸鸡蛋

**Comment by hylarucoder** [comment]
## 04-02

## 锻炼

- [x] 骑车 40min
- [x] 深蹲 220 

## 饮食

- 早餐: 美式拿铁+鸡胸肉150g
- 午餐: 三菜, 不吃米饭
- 晚餐: 鸡胸肉150g

## 体重 

- 177

**Comment by hylarucoder** [comment]
## 2021-04-03

## 锻炼

- 无绳跳绳 1000
- 推拉 800

## 饮食

- 早餐: 鸡胸肉 + 面皮 + 牛奶300ml
- 午餐: 鸡胸肉 + 面皮 + 牛奶300ml
- 晚餐: 鸡胸肉 + 面皮 + 牛奶300ml

**Comment by hylarucoder** [comment]
## 2021-04-04

## 锻炼

- [x] 休息

## 饮食

- 早餐: 鸡胸肉 + 包子
- 午餐: 炸鸡
- 晚餐: 鸡胸肉 + 馄饨

**Comment by hylarucoder** [comment]
## 2021-04-05

## 锻炼

- [x] 5公里+ 20分钟自行车

## 饮食

- 早餐: 鸡胸肉 + 面皮
- 午餐: 苹果 x 2
- 晚餐: 鸡胸肉

**Comment by hylarucoder** [comment]
## 04-06

## 锻炼

- [x] 健身环 140 深蹲
- [x] 20 min 自行车 x 2
- [ ] 推拉1000次(失败)

## 饮食

- 早餐: 美式拿铁
- 午餐: 饺子
- 晚餐: 鸡胸肉

**Comment by ggggarlic** [comment]
## 04-06

## 锻炼

- [x] 跳绳 2000
- [x] Hit 15 分钟

## 饮食
- 早餐: 热美式咖啡 + 肉松面包 2 小块 (20g)
- 午餐: 青菜 + 燕麦 + 炒肉
- 晚餐: 蒸鸡蛋

>Ex:  近半个月以有氧运动为主,现身体的心肺功能有明显的提升. 开始增加一些对抗性以及 `Hit` 相对对抗性较强的运动, 开始针对性减值.

> 吐槽: 小米手环 6 是真的拉胯, 无缘无故就开始丢运动数据... 超级影响体验. 闲鱼拍了个小米运动手表 Color, 如果再丢, 退 `Mifans`. 

## 体重
- 174.4斤

**Comment by ggggarlic** [comment]
## 04-07

## 锻炼

- [x] 跳绳 3000

## 饮食
- 早餐: 面包两块 + 低脂牛奶
- 午餐: 排骨汤 + 芹菜炒豆干
- 晚餐: 蒸鸡蛋

>  完蛋, 昨天做了 `Hit` 今天直接拉胯.  不知不觉就达到乳酸阈值了...  肌肉酸痛...  今天适当减轻运动量, 并增加一些拉伸.

## 体重 (近 7 次均值)
- 175.62 斤

> 今天跳绳的时候直接上 `150bpm` 的 `edm` , 直接加速快跑模式, 终于在 `25` 分钟跳完 `3000` 了, 开心. 不过小米手环 5 继续丢运动数据.

**Comment by hylarucoder** [comment]
## 04-07

满意

## 锻炼

- [x] 健身环 1小时 
- [x] 220 深蹲
- [x] 20 min 自行车 x 2

## 饮食

- 早餐: 鸡胸肉 + 美式拿铁
- 午餐: 披萨
- 晚餐: 鸡胸肉

## 体重

178.4 斤

**Comment by hylarucoder** [comment]
## 04-08

满意

## 锻炼

- [x] 健身环 30min
- [x] 500 推拉
- [x] 20 min 自行车 x 2
- [x] 哑铃 100

## 饮食

- 早餐: 鸡胸肉 + 美式拿铁
- 午餐: 三菜无饭
- 晚餐: 鸡胸肉

## 体重

177.0 斤

**Comment by ggggarlic** [comment]
## 04-08

## 锻炼

- [x] 跳绳 3000

## 饮食
- 早餐: 汤达人豚骨拉面半碗 + 橙子 + 低脂牛奶
- 午餐: 
- 晚餐: 蒸鸡蛋

>  今天继续肌肉酸痛...  可能是因为昨天跳绳太猛了, 不过很享受.  最近增加了腿部的肌肉拉伸, 效果还不错

## 体重 
- 172.4 斤

**Comment by hylarucoder** [comment]
## 04-09

满意

## 锻炼

状态一般, 水了一天

- [x] 健身环 30min
- [x] 20 min 自行车
- [x] 20 min 自行车
- [x] 500 推拉
- [ ] 哑铃 100

## 饮食

- 早餐: 鸡胸肉 + 美式拿铁
- 午餐: 三菜无饭
- 晚餐: 鸡胸肉

## 体重

176.0 斤

**Comment by ggggarlic** [comment]
## 04-09
今天懈怠了...  

## 锻炼

- [x]  跳绳 1500

## 饮食
早餐:  带肉火锅
午餐:  素火锅
晚餐: 蒸鸡蛋

## 体重
174 斤

**Comment by hylarucoder** [comment]
## 04-10

未运动, 步走16800步

## 饮食

- 早餐: 面包
- 午餐: 饺子大份
- 晚餐: 三菜无饭

**Comment by ggggarlic** [comment]
## 04-10
一定要抽时间运动呀@@@

## 锻炼
- [x] 跳绳 3000

## 饮食
早餐: 玉米豌豆炒胡萝卜 + 蒸茄子青菜 + 1/3 小碗米饭
午餐: 炒蛏子 + 炒蛤蜊 + 泡燕麦(无糖)
晚餐: 蒸鸡蛋 x 3

## 体重
172.1 斤

> PS: 决定 165 ~ 162 斤时候再增加对抗性运动.

**Comment by hylarucoder** [comment]
## 04-11

未运动, 步走18800步

## 饮食

- 早餐: 粉丝 + 生煎 + 馄炖
- 午餐: 辣子鸡丁 + 粉丝
- 晚餐: 苹果

**Comment by ggggarlic** [comment]
## 04-11

## 锻炼
- [x]跳绳 4000


## 饮食
早餐:  1/3 李子柒螺蛳粉 + 一头小白菜
午餐:  小纸杯蛋糕 x 4 + 饺子 x 4 
晚餐: 蒸鸡蛋 x 3

## 体重
170.7 斤

**Comment by hylarucoder** [comment]
## 04-12

满意

## 锻炼

- [x] 健身环 55min (150深蹲)
- [x] 20 min 自行车
- [x] 20 min 自行车
- [ ] 哑铃 100

## 饮食

- 早餐: 鸡胸肉 + 美式拿铁
- 午餐: 披萨
- 晚餐: 鸡胸肉 + 苹果

## 体重

178.0 斤

**Comment by ggggarlic** [comment]
## 04-12

## 锻炼
[x]跳绳 3000

## 饮食
早餐:  2/3 袋方便面 + 鸡蛋
午餐:  炖排骨200g + 卤鹅 100g + 米饭 1/3 小碗 + 西蓝花
晚餐:  橙子 x 2

## 体重
170.2 斤

> 啊啊啊  两天几乎没动啦,,,   明天直接加对抗训练...  加油! 160 档有望啦!

**Comment by hylarucoder** [comment]
## 04-13

满意

## 锻炼

- [x] 跳绳3000
- [x] 20 min 自行车
- [x] 20 min 自行车
- [x] 哑铃100

## 饮食

- 早餐: 鸡胸肉 + 苹果 + 美式拿铁
- 午餐: 牛肉粉丝汤+烧饼x2
- 晚餐: 鸡胸肉 + 苹果

## 体重

177.0 斤

**Comment by ggggarlic** [comment]
## 04-13

## 锻炼

- [x] 跳绳 4000

## 饮食
早餐: 干拌方便面
午餐: 春饼套餐 x 1 + 酱排骨 x 1 + 蔬菜
晚餐: 橙子 x 1

## 体重
169.1 斤

> 可以了今天...  稳定 160+ 了... 最近没有在吃鸡蛋了, 貌似吃了会有些过敏, 头痛.

**Comment by hylarucoder** [comment]
## 04-14

满意

## 锻炼

- [x] 跳绳1000
- [x] 跳绳3000
- [x] 20 min 自行车
- [x] 20 min 自行车

## 饮食

- 早餐: 鸡胸肉 +  美式拿铁
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

177.0 斤

**Comment by hylarucoder** [comment]
## 04-15

满意

## 锻炼

- [x] 跳绳3000
- [x] 20 min 自行车
- [x] 20 min 自行车

## 饮食

- 早餐: 鸡胸肉 +  美式拿铁 + 司康
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

175.0 斤

**Comment by ggggarlic** [comment]
## 04-14
## 锻炼

- [x ] 跳绳 1500

- [x ] keep 30min

## 饮食
早餐:  无
午餐:  无
晚餐:  油焖大虾 + 米饭 1/3 碗
加餐: 鸭头 鸭爪

## 体重
170.1 斤

> 直接没吃饭怼了 Keep, 直接低血糖了 ... 以后不能这么刚了.

**Comment by ggggarlic** [comment]
## 04-15
## 锻炼

- [x] 跳绳  3000

## 饮食
早餐:  豆浆 + 三明治
午餐:  方便面
晚餐:   蛤蜊 + 蛏子 + 1/2 米饭

加餐: 卤鸭头... 


## 体重
169.7 斤

> PS 不能再加餐了... 管住嘴...

**Comment by hylarucoder** [comment]
## 04-16

水一天

## 锻炼

- [x] 20 min 自行车
- [x] 20 min 自行车

## 饮食

- 早餐: 鸡胸肉 +  美式拿铁
- 午餐: 三菜
- 晚餐: 面皮x2 + 炸鸡

## 体重

174.0 斤

**Comment by ggggarlic** [comment]
## 04-16
## 锻炼

- [x] 跳绳  5000

## 饮食
早餐:  低脂牛奶 + 吐司面包 x 2
午餐:  开元米粉 1/10 + 胡萝卜 + 蟹肉棒1 袋 + 小白菜 x 1 头
晚餐:   春饼 1 份 + 饺子 x 1 

> PS 加餐忍住了 , 老婆自己吃的.  

## 体重
169.3 斤

**Comment by hylarucoder** [comment]
## 04-17


## 锻炼

- [x] 跳绳5000

## 饮食

- 早餐: 无
- 午餐: 鸡胸肉
- 晚餐: 鸡胸肉 + 香瓜 + 香蕉

## 体重

175.0 斤

**Comment by ggggarlic** [comment]
## 04-17
## 锻炼

- [x] 跳绳 1000

## 饮食
早餐:  无
午餐:  火锅
晚餐:  火锅

>  完蛋, 周末家里来客人了... 就大吃大喝了.  

## 体重
170.1 斤

**Comment by ggggarlic** [comment]
## 04-18
## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:  无
午餐:  东北菜
晚餐:   螺蛳粉 1/5

## 体重
169.5

**Comment by hylarucoder** [comment]
## 04-18


## 锻炼

- [x] 跳绳3000

## 饮食

- 早餐: 鸡胸肉
- 午餐: 香蕉x2 + 鸡胸肉
- 晚餐: 小龙虾

## 体重

175.0 斤

**Comment by hylarucoder** [comment]
## 04-19


## 锻炼

- [x] 跳绳3000
- [x] 骑车20min
- [x] 跳绳5000
- [x] 骑车20min

## 饮食

- 早餐: 牛奶
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

175.0 斤

**Comment by ggggarlic** [comment]
## 04-19
## 锻炼

- [x] 跳绳 7000

## 饮食
早餐:  吐司面包 x 2
午餐:   猪排 x 1 + 西兰花
晚餐:   排骨 + 鸡胸肉 + 西兰花

## 体重
168.1 斤

> PS  终于开始往下走了, 而且 BMI 降低到 "偏高" 区间了 (之前是"高").

**Comment by hylarucoder** [comment]
## 04-20

## 锻炼

- [x] 跳绳3000
- [x] 骑车20min
- [x] 跳绳4000
- [x] 骑车20min

## 饮食

- 早餐: 鸡胸肉
- 午餐: 三菜
- 晚餐: 鸡胸肉 + 牛奶

## 体重

173.0 斤

**Comment by ggggarlic** [comment]
## 04-20
## 锻炼

- [x] 跳绳 3000
- [x] 跑步 1km / 4min

## 饮食
早餐:   吐司面包 x 1
午餐:   鸡胸肉 + 鸡骨架 + 1/5 米饭
晚餐:   皮皮虾 + 卤鹅 + 带鱼 + 蛤蜊  + 1/5 米饭

## 体重
169.5 斤



> 家里同小区朋友来家里住几天 ... 然后现在就下楼跳绳去了... 
>  哎 , 吃多了吃多了 ...  看明天多拉一些吧.

**Comment by hylarucoder** [comment]
## 04-21

## 锻炼

- [x] 跳绳2000
- [x] 骑车20min
- [x] 跳绳3000
- [x] 骑车20min

## 饮食

- 早餐: 鸡胸肉 + 美式
- 午餐: 三菜
- 晚餐: 鸡胸肉 + 牛奶 + 香瓜

## 体重

172.2 斤

**Comment by ggggarlic** [comment]
## 04-21
## 锻炼

- [x] 跳绳 4000

## 饮食
早餐:  萨其马 x1 +  肉松饼 x1 
午餐:   汤达人方便面 x1
晚餐:   皮皮虾 + 基围虾 + 米饭 1/3 

## 体重
169.5 斤

**Comment by hylarucoder** [comment]
## 04-22

水一天, 今天不动

## 锻炼

- [x] 骑车20min
- [x] 骑车20min

## 饮食

- 早餐: 鸡胸肉 + 美式
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

170.6 斤

**Comment by ggggarlic** [comment]
## 04-22
## 锻炼

- [x] 跳绳 3000 

## 饮食
早餐:   无
午餐:   吐司蛋糕 x 2
晚餐:   炒大虾 + 1/3 米饭

## 体重

167.3 斤

**Comment by hylarucoder** [comment]
## 04-23

晚上吃的太多

## 锻炼

- [x] 骑车20min
- [x] 骑车20min
- [x] 跳绳 2000

## 饮食

- 早餐: 美式 + 包子x2
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

171.6 斤

**Comment by twocucao** [comment]
## 04-23

## 锻炼

- [x] 骑车20min
- [ ] 骑车20min
- [x] 跳绳 2000
- [x] 哑铃 x100
- [ ] 跳绳 5000


## 饮食

- 早餐: 美式 + 包子x2
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

170.6 斤

**Comment by twocucao** [comment]
## 04-23

## 锻炼

- [x] 骑车20min
- [ ] 骑车20min
- [x] 跳绳 2000
- [x] 哑铃 x100
- [ ] 跳绳 5000


## 饮食

- 早餐: 美式 + 包子x2
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

170.6 斤

**Comment by hylarucoder** [comment]
## 04-24

昨天吃的太多, 反弹了

## 锻炼

- [x] 散步5公里
- [x] 跳绳 3500

## 饮食

- 早餐: 卷皮x2
- 午餐: 麻辣烫
- 晚餐: 鸡胸肉 + 苹果

## 体重

173 斤

**Comment by ggggarlic** [comment]
## 04-23
## 锻炼

- [x] 跳绳 7000

## 饮食
早餐:   无
午餐:   方便面
晚餐:   西蓝花 + 秋葵 + 蒸鱼 + 1/2 米饭

## 体重

167.8 斤

**Comment by ggggarlic** [comment]
## 04-24
## 锻炼

- [x] 跳绳 1000

## 饮食
早餐:   无
午餐:    鸡胸肉 + 全麦面
晚餐:   肯德基炸鸡桶

## 体重

168 斤


> 周末老婆没在家... 自己只能点外卖了.

**Comment by hylarucoder** [comment]
## 04-25

## 锻炼

- [x] 骑车20min
- [x] 跳绳5000
- [x] 骑车20min

## 饮食

- 早餐: 美式
- 午餐: 三菜 + 馒头
- 晚餐: 鸡胸肉 + 牛奶

## 体重

173.0 斤

**Comment by hylarucoder** [comment]
## 04-26

## 锻炼

- [x] 骑车20min
- [x] 跳绳2000
- [x] 骑车20min
- [x] 跳绳6000

## 饮食

- 早餐: 美式
- 午餐: 三菜 
- 晚餐: 鸡胸肉 + 牛奶

## 体重

171.0 斤

**Comment by hylarucoder** [comment]
## 04-27

## 锻炼

- [x] 骑车20min
- [x] 骑车20min
- [x] 跳绳5000

## 饮食

- 早餐: 饼干 + 卤蛋
- 午餐: 披萨
- 晚餐: 鸡胸肉

## 体重

169.8 斤

**Comment by ggggarlic** [comment]
## 04-25
## 锻炼

- [x] 跳绳 7000

## 饮食
早餐:   无
午餐:    鸡胸肉 + 全麦面
晚餐:   鸡胸肉 + 全麦面

## 体重

167 斤

**Comment by ggggarlic** [comment]
## 04-26
## 锻炼

- [x] 跳绳 4000

## 饮食
早餐:   无
午餐:    鸡胸肉 + 全麦面
晚餐:   鸡胸肉 + 全麦面

## 体重

167 斤

**Comment by ggggarlic** [comment]
## 04-27
## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:   无
午餐:   卤鹅饭 
晚餐:   饺子

## 体重

166.3 斤

**Comment by ggggarlic** [comment]
## 04-28
## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:   吐司面包 x1  低脂牛奶
午餐:    鸡胸肉  青菜  西兰花  燕麦
晚餐:   玉米 青豆炒饭

## 体重
166.2

**Comment by hylarucoder** [comment]
## 04-28

晚上食欲太好吃多了....

## 锻炼

- [x] 骑车20min
- [x] 骑车20min
- [x] 哑铃200

## 饮食

- 早餐: 鸡胸肉
- 午餐: 三菜
- 晚餐: 鸡胸肉 + 炸鸡 + 饺子

## 体重

168.6 斤

**Comment by hylarucoder** [comment]
## 04-29

## 锻炼

- [x] 骑车20min
- [x] 骑车20min
- [x] 跳绳5200

## 饮食

- 早餐: 鸡胸肉
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

170 斤

**Comment by ggggarlic** [comment]
## 04-29
## 锻炼

- [x] 跳绳 3000

## 饮食
早餐:   吐司面包
午餐:   方便面
晚餐:  无

## 体重

165.2 斤

**Comment by hylarucoder** [comment]
## 04-30

## 锻炼

- [x] 骑车20min
- [x] 跳绳3000
- [x] 骑车20min
- [x] 跳绳5350


## 饮食

- 早餐: 鸡胸肉 + 拿铁
- 午餐: 三菜
- 晚餐: 鸡胸肉

## 体重

169 斤

**Comment by hylarucoder** [comment]
closed for https://github.com/twocucao/the-road-to-fitness/issues/17

![image](https://user-images.githubusercontent.com/5625783/116697515-d9238f00-a9f5-11eb-912c-9836e4d8f891.png)
