### ISSUE TITLE
建议学习一些基础的营养知识

### ISSUE THREAD

**Issue by junlinguo11** [twocucao/the-road-to-fitness#8]
了解为了达成你的目标需要吃什么，为什么要这样吃，并对不同食物热量/营养成分有概念。
祝减肥成功！

**Comment by hylarucoder** [comment]
@junlinguo11 谢谢建议哈, 我会陆陆续续更新这方面的知识. 

目前来说, 我的基本减肥思路是加大运动量+减少饭量, 等减到了大约150的时候, 我就开始调整膳食结构.
